name: 'Templates Deployment'
description:
  'This action will take a build artifact, and arrange it in a JSON format, all
  build directory must be in HTML as the subfolders files.'
author: 'Aytomic Technology'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
